 <?php

// Edit this file to your langugage

$lang = array(
  "warning"                               => "Warning!",
  "login"                                 => "Login",
  "register"                              => "Register",
  "please_sign_in"                        => "Please sign in",  
  "password"                              => "Password",
  "password_repeat"                       => "Password (repeat)",
  "remember_me"                           => "Remember me",
  "sign_in"                               => "Sign in",
  "create_member"                         => "Create a member",
  "you_were_logged_out"                   => "You were logged out!",
  
  "sounds"                                => "Sounds",
  "visible"                               => "Visible",
  "profile"                               => "Profile",
  "change_password"                       => "Change password",
  "administration"                        => "Administration",
  "settings"                              => "Settings",
  "users"                                 => "Users",
  "add_user"                              => "Add user",
  "manage"                                => "Manage",
  "rooms"                                 => "Rooms",
  "add_room"                              => "Add room",
  "logout"                                => "Logout",
  "page"                                  => "Page",
  
  "online_users"                          => "Online users",
  "response"                              => "Response",
  "send"                                  => "Send",
  "upload_file"                           => "Upload file",
  "loading_older"                         => "Loading older ...",
  "start_chat_with"                       => "Start chat with ...",
  "online"                                => "Online",
  "change_avatar"                         => "Change avatar",
  "delete_avatar"                         => "Delete avatar",
  "ban"                                   => "Ban",
  "informations"                          => "Informations",
  "edit"                                  => "Edit",
  "discard"                               => "Discard",
  "save_changes"                          => "Save changes",
  "now_using_password"                    => "Now using password",
  "new_password"                          => "New password",
  "repeat_new_password"                   => "Repeat new password",
  "settings"                              => "Settings",
  "save_settings"                         => "Save settings",
  "banned"                                => "Banned",
  "last_login"                            => "Last login",
  "registered"                            => "Registered",
  
  "check_empty_fields"                    => "Check empty fields!",
  "this_account_has_ban"                  => "This account has a ban!",
  "check_login_and_password"              => "Check login and password!",
  "login_contain"                         => "Login can contain characters a-z and numbers 0-9, length must be 3-15!",
  "passwords_not_match"                   => "Passwords not match!",
  "login_is_already_using"                => "Login is already using!",
  "internal_error"                        => "Internal error!",
  "not_permitted"                         => "Not permitted!",
  "incorrect_old_password"                => "Incorrect old password!",
  "password_successfully_changed"         => "Password successfully changed!",
  
  "write_text"                            => "Write text!",
  "too_long_message"                      => "Too long message!",
  "uploading"                             => "Uploading...",
  
  "site_name"                             => "Site name",
  "profile_items"                         => "Profile items",
  "profile_items_warning"                 => "Insert as 'key':'value', 'key':'value1' ...",
  "refresh_delay"                         => "Refresh delay",
  "refresh_delay_info"                    => "Delay for getting the newest data",
  "milisecond"                            => "ms",
  "delay_for_offline"                     => "Delay for offline",
  "second"                                => "sec",
  "delay_for_offline_info"                => "Delay in which user must send refresh request",
  "attachment_max_size"                   => "Attachment max.size",
  "megabyte"                              => "MB",
  "enabled_private_messages"              => "Enabled private messages",
  "enabled_registration"                  => "Enabled registration",
  "enabled_registration_info"             => "If registration disabled only administrator can add user",
  "max_characters_in_message"             => "Max. count of characters in message",
  "messages_per_page"                     => "Count of messages per page",
  "datetime_format"                       => "Datetime format",
  "datetime_format_info"                  => "Check <a href='http://php.net/manual/en/function.date.php#refsect1-function.date-parameters' target='_blank'>PHP Function date()</a>",
  "available_attachments_for_members_at"  => "Available attachments for members at:",
  "private_messages"                      => "Private messages",
  "administrator"                         => "Administrator",
  "member"                                => "Member",
  "settings_bottom_info"                  => "[ Page load required to apply settings ]",
  "level"                                 => "Level",
  "user_successfully_added"               => "User successfully added",
  "user_successfully_updated"             => "User successfully updated",
  "unknown_level"                         => "Unknown level",
  "yes"                                   => "Yes",
  "no"                                    => "No",
  "manage_users"                          => "Manage users",
  "id"                                    => "ID",
  "actions"                               => "Actions",
  "delete"                                => "Delete",
  "are_you_sure"                          => "Are you sure?",
  "edit_user"                             => "Edit user",
  
  "select_name_for_new_room"              => "Select name for new room:",
  "name"                                  => "Name",
  "select_new_name"                       => "Select new name",
  "manage_rooms"                          => "Manage rooms",
  
  //added in 2.1
  "direction_rtl"                         => "Direction right-to-left",
  "next_message_delay"                    => "Time delay to send next message",
  "you_are_too_fast"                     => "Your are too fast!"
);